import { AlgorithmInfo, AlgorithmKey } from './types';

export const ALGORITHM_DATA: Record<AlgorithmKey, AlgorithmInfo> = {
  'bubble-sort': {
    key: 'bubble-sort',
    name: 'Bubble Sort',
    category: 'sorting',
    bestTime: 'O(n)',
    avgTime: 'O(n²)',
    worstTime: 'O(n²)',
    spaceComplexity: 'O(1)',
    stable: true,
    inPlace: true,
    description:
      'Bubble Sort repeatedly steps through the list, compares adjacent elements, and swaps them if they are in the wrong order. Pass through the list is repeated until the list is sorted.',
    pseudocode: [
      'procedure bubbleSort(A : list of sortable items)',
      '  n := length(A)',
      '  repeat',
      '    swapped := false',
      '    for i := 1 to n-1 do',
      '      if A[i-1] > A[i] then',
      '        swap(A[i-1], A[i])',
      '        swapped := true',
      '  until not swapped',
      'end procedure',
    ],
  },
  'selection-sort': {
    key: 'selection-sort',
    name: 'Selection Sort',
    category: 'sorting',
    bestTime: 'O(n²)',
    avgTime: 'O(n²)',
    worstTime: 'O(n²)',
    spaceComplexity: 'O(1)',
    stable: false,
    inPlace: true,
    description:
      'Selection Sort divides the input list into two parts: a sorted sublist built up from left to right and an unsorted sublist. It repeatedly selects the smallest element from the unsorted sublist and moves it to the sorted sublist.',
    pseudocode: [
      'procedure selectionSort(A : list of sortable items)',
      '  n := length(A)',
      '  for i := 0 to n-2 do',
      '    minIndex := i',
      '    for j := i+1 to n-1 do',
      '      if A[j] < A[minIndex] then',
      '        minIndex := j',
      '    if minIndex != i then',
      '      swap(A[i], A[minIndex])',
      'end procedure',
    ],
  },
  'insertion-sort': {
    key: 'insertion-sort',
    name: 'Insertion Sort',
    category: 'sorting',
    bestTime: 'O(n)',
    avgTime: 'O(n²)',
    worstTime: 'O(n²)',
    spaceComplexity: 'O(1)',
    stable: true,
    inPlace: true,
    description:
      'Insertion Sort builds the final sorted array one item at a time. It takes each element from the unsorted portion and inserts it into its correct position within the sorted portion.',
    pseudocode: [
      'procedure insertionSort(A : list of sortable items)',
      '  for i := 1 to length(A)-1 do',
      '    key := A[i]',
      '    j := i - 1',
      '    while j >= 0 and A[j] > key do',
      '      A[j + 1] := A[j]',
      '      j := j - 1',
      '    A[j + 1] := key',
      'end procedure',
    ],
  },
  'merge-sort': {
    key: 'merge-sort',
    name: 'Merge Sort',
    category: 'sorting',
    bestTime: 'O(n log n)',
    avgTime: 'O(n log n)',
    worstTime: 'O(n log n)',
    spaceComplexity: 'O(n)',
    stable: true,
    inPlace: false,
    description:
      'Merge Sort is a Divide and Conquer algorithm. It divides the input array into two halves, recursively sorts them, and then merges the two sorted halves back together.',
    pseudocode: [
      'procedure mergeSort(A, left, right)',
      '  if left < right then',
      '    mid := (left + right) / 2',
      '    mergeSort(A, left, mid)',
      '    mergeSort(A, mid + 1, right)',
      '    merge(A, left, mid, right)',
      'end procedure',
      '',
      'procedure merge(A, left, mid, right)',
      '  create leftArray and rightArray',
      '  while elements remain in both subarrays do',
      '    compare and insert smallest into A',
      '  copy remaining elements',
    ],
  },
  'quick-sort': {
    key: 'quick-sort',
    name: 'Quick Sort',
    category: 'sorting',
    bestTime: 'O(n log n)',
    avgTime: 'O(n log n)',
    worstTime: 'O(n²)',
    spaceComplexity: 'O(log n)',
    stable: false,
    inPlace: true,
    description:
      'Quick Sort selects a "pivot" element from the array and partitions the other elements into two sub-arrays according to whether they are less than or greater than the pivot, then recursively sorts the sub-arrays.',
    pseudocode: [
      'procedure quickSort(A, low, high)',
      '  if low < high then',
      '    pivotIndex := partition(A, low, high)',
      '    quickSort(A, low, pivotIndex - 1)',
      '    quickSort(A, pivotIndex + 1, high)',
      'end procedure',
      '',
      'procedure partition(A, low, high)',
      '  pivot := A[high]',
      '  i := low - 1',
      '  for j := low to high - 1 do',
      '    if A[j] < pivot then',
      '      i := i + 1, swap A[i] with A[j]',
      '  swap A[i + 1] with A[high]',
      '  return i + 1',
    ],
  },
  'heap-sort': {
    key: 'heap-sort',
    name: 'Heap Sort',
    category: 'sorting',
    bestTime: 'O(n log n)',
    avgTime: 'O(n log n)',
    worstTime: 'O(n log n)',
    spaceComplexity: 'O(1)',
    stable: false,
    inPlace: true,
    description:
      'Heap Sort converts the array into a Max-Heap data structure. It repeatedly extracts the maximum element from the root and restores the heap property until all elements are sorted.',
    pseudocode: [
      'procedure heapSort(A)',
      '  n := length(A)',
      '  for i := n/2 - 1 down to 0 do',
      '    heapify(A, n, i)',
      '  for i := n-1 down to 1 do',
      '    swap A[0] with A[i]',
      '    heapify(A, i, 0)',
      'end procedure',
      '',
      'procedure heapify(A, n, i)',
      '  largest := i, left := 2*i + 1, right := 2*i + 2',
      '  if left < n and A[left] > A[largest] then largest := left',
      '  if right < n and A[right] > A[largest] then largest := right',
      '  if largest != i then swap A[i], A[largest]; heapify(A, n, largest)',
    ],
  },
  'linear-search': {
    key: 'linear-search',
    name: 'Linear Search',
    category: 'searching',
    bestTime: 'O(1)',
    avgTime: 'O(n)',
    worstTime: 'O(n)',
    spaceComplexity: 'O(1)',
    stable: true,
    inPlace: true,
    description:
      'Linear Search sequentially checks each element of the list from start to finish until a match for the target value is found or the end of the list is reached.',
    pseudocode: [
      'procedure linearSearch(A, target)',
      '  n := length(A)',
      '  for i := 0 to n-1 do',
      '    if A[i] == target then',
      '      return i  // Target found at index i',
      '  return -1     // Target not found in array',
      'end procedure',
    ],
  },
  'binary-search': {
    key: 'binary-search',
    name: 'Binary Search',
    category: 'searching',
    bestTime: 'O(1)',
    avgTime: 'O(log n)',
    worstTime: 'O(log n)',
    spaceComplexity: 'O(1)',
    stable: true,
    inPlace: true,
    description:
      'Binary Search works on sorted arrays. It repeatedly divides the search interval in half by comparing the target value to the middle element until the target is found or the interval is empty.',
    pseudocode: [
      'procedure binarySearch(A, target)',
      '  low := 0, high := length(A) - 1',
      '  while low <= high do',
      '    mid := floor((low + high) / 2)',
      '    if A[mid] == target then',
      '      return mid  // Target found at index mid',
      '    else if A[mid] < target then',
      '      low := mid + 1',
      '    else',
      '      high := mid - 1',
      '  return -1  // Target not found',
      'end procedure',
    ],
  },
};
